#!/bin/bash
# shellcheck shell=bash

echo "Integrating custom indexers..."

if [ -d /opt/custom-indexers ]; then
    mkdir -p /config/Definitions/Custom
    cp -f /opt/custom-indexers/*.yml /config/Definitions/Custom/
    echo "Custom indexers copied to /config/Definitions/Custom"
else
    echo "No custom indexers found in /opt/custom-indexers"
fi
